name: Publish Package to NuGet

on:
  push:
    branches:
      - master

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore dependencies
        run: dotnet restore src/TrophyApi.sln

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Install libssl dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev

      - name: Build
        run: |
          export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
          dotnet build src/TrophyApi.sln --configuration $BUILD_CONFIG --no-restore

      - name: Run tests
        run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal

      - name: Publish
        run: dotnet nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
